@echo off
echo Updating scan request policies to allow doctors to see all scan requests...
powershell -ExecutionPolicy Bypass -File "%~dp0update-scan-request-policies.ps1"
echo Done! Press any key to exit...
pause > nul
